version: "3.2"
services:
        web:
                build: .
                container_name: flask_web
                command: poetry run gunicorn wsgi:app
                ports:
                        - "5000:5000"
                depends_on:
                        - redis

        worker:
                build: .
                container_name: rq_worker
                command: poetry run flask rq worker
                depends_on:
                        - redis

        scheduler:
                build: .
                container_name: rq_scheduler
                command: poetry run flask rq scheduler
                depends_on:
                        - redis

        redis:
                image: "redis:alpine"
                command: redis-server --requirepass password
                ports:
                        - "6379:6379"
                volumes:
                        - $PWD/redis-data:/var/lib/redis
                        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
                environment:
                        - REDIS_REPLICATION_MODE=master
